name: "Certification Preparation"
description: "Track progress for a certification"
title: "[CERT]: "
labels: ["certification"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a certification tracking issue!
        Please fill in the information below.

  - type: input
    id: cert-name
    attributes:
      label: "Certification Name"
      description: "What certification are you preparing for?"
      placeholder: "AWS Solutions Architect Professional"
    validations:
      required: true

  - type: textarea
    id: objectives
    attributes:
      label: "Learning Objectives"
      description: "List the key areas you need to master"
      placeholder: |
        - Master advanced networking concepts
        - Deep dive into security best practices
        - Understand multi-account strategies
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How urgent is this certification?"
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: "Study Resources"
      description: "List the resources you plan to use"
      placeholder: |
        - Official documentation
        - Online courses
        - Practice tests